### ISSUE TITLE
Beta 14 issues

### ISSUE THREAD

**Issue by requilence** [FriendsOfFlarum/doorman#29]
I got this after i've installed and enabled the new updated fof/doorman (v0.2.0)
It seems to work (sign up checks the invite code correctly), but I can't open settings in the admin panel to add new codes – it does nothing and produces no log in Console or network request

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/1025231/101177580-a6e15180-3650-11eb-91d3-72cfa1b90fa5.png">

**Comment by requilence** [comment]
Ok, so doorman settings are located on a separate page. So besides this error on install, there are no other problems

**Comment by karaok491** [comment]
Hi there, and thanks for the report.

I've found a small typo in the settings config that would stop the settings panel opening after the extension was enabled, and have already pushed a fix for that (not yet tagged)

The boot error, I cannot seem to replicate here. Did you remember to run `php flarum cache:clear` after the installation of the extension maybe?

**Comment by imorland** [comment]
Closing as stale. Please re-open if you still have this issue
