### ISSUE TITLE
beta 15 issue

### ISSUE THREAD

**Issue by bd8670** [FriendsOfFlarum/doorman#33]
Keep getting this message when trying to install:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires fof/doorman ^0.3.0 -> satisfiable by fof/doorman[0.3.0].
    - fof/doorman 0.3.0 requires flarum/core ^0.1.0-beta-15 -> found flarum/core[dev-master, v0.1.0-beta.15, 0.1.x-dev (alias of dev-master)] but it does not match your minimum-stability.

Installation failed, deleting ./composer.json.

**Comment by datitisev** [comment]
Hm looks like it's because it requires `beta-15` instead of `beta.15`... 🤔

**Comment by bd8670** [comment]
I'm a non-technical 100% newbie, so pardon me if my question is way off.
Could I get a hint on how to resolve my problem?

**Comment by datitisev** [comment]
I don't think you'll be able to; we have to fix the version requirement of Flarum in this extension.

**Comment by the-turk** [comment]
**issue should be closed**
