### ISSUE TITLE
An API for invitation code generation/addition

### ISSUE THREAD

**Issue by hahagu** [FriendsOfFlarum/doorman#44]
## Feature Request

Currently, there is no way to automate the process of adding a key.

**Describe the solution you'd like**

An API access point (URL, POST) so that invitation codes can be added automatically from other apps,
generated on the fly by request, and deleted/disabled on request.

This would allow, for example, a wordpress site to issue it's own unique one time use code and automatically hand it to the user, without having the administrator manually intervene and issue one themselves and give them to the users.

You can see how this would stack up if there are lots of users that you want individual invite codes for.

**Describe alternatives you've considered**

I guess a macro could work, but it is not practical.

**Comment by Gongcxgithub** [comment]
I agree that the Doorman plug-in should provide an API access point that support the use of POST request types to automate the creation of invitation codes. Hopefully the developers will see this Issue.

**Comment by dsevillamartin** [comment]
This has been possible for a couple of years. The endpoint `/api/fof/doorkeys` is used to fetch & create doorkeys, and `/api/fof/doorkeys/{id}` is used to edit & delete them.
