### ISSUE TITLE
Email modal no longer works

### ISSUE THREAD

**Issue by luceos** [FriendsOfFlarum/doorman#45]
## Bug Report

When you have created an invite code, the email button doesn't work and throws errors in console.

**Screenshots**

<img width="454" alt="image" src="https://user-images.githubusercontent.com/504687/161293411-26d961a1-f9f5-4b7c-919f-244b8f97561c.png">

**Environment**
- Flarum version: 1.2.0
- Extension version: 1.0.1

**Comment by imorland** [comment]
Fixed in `1.1.0`
